<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LOGIN</name>
   <tag></tag>
   <elementGuidId>d23d255e-14e5-40f9-b0f0-82a13d5ee65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rootLink.ghost-button-green.fx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='globalNavigation']/b/b/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87016756-5356-4344-ae74-1b4048fc8086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rootLink ghost-button-green fx</value>
      <webElementGuid>b38cdff8-d97c-4820-943b-c91fa454ff23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-adroll-segment</name>
      <type>Main</type>
      <value>submit_two</value>
      <webElementGuid>5c256d5d-fb5d-477c-95d9-528cd36867d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webappv1/#/login?entry_point=landing-page</value>
      <webElementGuid>49e39eca-6642-4dd1-815e-7e6e7ee73f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  LOGIN
                </value>
      <webElementGuid>7b5e9c17-a5ad-4ee2-b7b7-1081d003002b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalNavigation&quot;)/b[1]/b[1]/div[@class=&quot;container-lg&quot;]/ul[@class=&quot;navRoot&quot;]/li[@class=&quot;navSection secondary&quot;]/a[@class=&quot;rootLink ghost-button-green fx&quot;]</value>
      <webElementGuid>8bb97141-adb1-45f3-badc-10b07a3a6eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='globalNavigation']/b/b/div/ul/li[3]/a</value>
      <webElementGuid>be8adf73-6f14-411c-821f-d40a32f7e088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGIN')]</value>
      <webElementGuid>de461315-ee43-48e1-a8e7-eb2e68c4bb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERUSAHAAN'])[1]/following::a[1]</value>
      <webElementGuid>397cfd14-fdea-49f4-9544-057c35b8d80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HARGA'])[1]/following::a[2]</value>
      <webElementGuid>e33eaf5e-3670-4ab8-8067-c99fe98e8700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR'])[1]/preceding::a[1]</value>
      <webElementGuid>a7c5b108-f24c-49c4-afc9-da8ebde98d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::a[2]</value>
      <webElementGuid>dfd76abc-4215-4311-9918-614c5f92bc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>24e86b86-193a-4c37-a352-5d20db50820a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/webappv1/#/login?entry_point=landing-page')]</value>
      <webElementGuid>becb0935-4b33-44e4-b9f8-88b3c4de9a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>a2a39fc0-d69e-4293-afae-6eeec9dff4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webappv1/#/login?entry_point=landing-page' and (text() = '
                  LOGIN
                ' or . = '
                  LOGIN
                ')]</value>
      <webElementGuid>c3645057-14d4-4805-985e-b118b6cfd291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
