<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>f234b4d9-4077-4a5f-8e50-dfc446935ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f811808-1d87-4a42-b496-58bb23ab01ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>250eebea-056b-4f9b-964d-d812580282e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>086b3aaf-2c13-41f2-aaca-ea75566ed1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email atau no. handphone Anda</value>
      <webElementGuid>7b9eae33-5db6-45d2-883f-a5cb47773882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>2bcbc91d-f2d2-49b3-90f4-00d18d21cf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ec7a4da8-ac22-4406-9503-84c51f405bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f32c619f-e06f-4882-ad2e-e0edf622d851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/app-root[1]/main[@class=&quot;normalize-modal&quot;]/auth-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;auth auth--blue&quot;]/div[@class=&quot;auth-grid&quot;]/div[1]/div[@class=&quot;auth-form__box&quot;]/form[@class=&quot;auth-mb-20 ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;auth-mb-40&quot;]/div[@class=&quot;auth-input-container&quot;]/input[@class=&quot;auth-input ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>8ceded69-96b6-414e-8fa3-a0b297cec7a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>abcb0233-8de2-4f6f-bb5f-657d64aede66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='main-body']/app-root/main/auth-login/div/div[2]/div/div/form/div/div[2]/input</value>
      <webElementGuid>07b84559-c5ef-4879-98a4-a95457d6593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5db2442a-3278-40fa-bec3-c72524214af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan email atau no. handphone Anda' and @name = 'email']</value>
      <webElementGuid>32fe97c7-9217-4408-ab4d-0457a5814da8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
